package edu.gdkm.po;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_admin.adminId
	 * @mbg.generated
	 */
	private Integer adminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_admin.account
	 * @mbg.generated
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_admin.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_admin.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_admin.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_admin.status
	 * @mbg.generated
	 */
	private String status;

	public Admin() {
	}

	public Admin(Integer adminId, String account, String password, String username, String email, String status) {
		this.adminId = adminId;
		this.account = account;
		this.password = password;
		this.username = username;
		this.email = email;
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_admin.adminId
	 * @return  the value of tb_admin.adminId
	 * @mbg.generated
	 */
	public Integer getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_admin.adminId
	 * @param adminId  the value for tb_admin.adminId
	 * @mbg.generated
	 */
	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_admin.account
	 * @return  the value of tb_admin.account
	 * @mbg.generated
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_admin.account
	 * @param account  the value for tb_admin.account
	 * @mbg.generated
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_admin.password
	 * @return  the value of tb_admin.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_admin.password
	 * @param password  the value for tb_admin.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_admin.username
	 * @return  the value of tb_admin.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_admin.username
	 * @param username  the value for tb_admin.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_admin.email
	 * @return  the value of tb_admin.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_admin.email
	 * @param email  the value for tb_admin.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_admin.status
	 * @return  the value of tb_admin.status
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_admin.status
	 * @param status  the value for tb_admin.status
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	@Override
	public String toString() {
		return "Admin [adminId=" + adminId + ", account=" + account + ", password=" + password + ", username="
				+ username + ", email=" + email + ", status=" + status + "]";
	}
	
}