package edu.gdkm.po;

public class Guest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestId
	 * @mbg.generated
	 */
	private Integer guestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestName
	 * @mbg.generated
	 */
	private String guestName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestPhone
	 * @mbg.generated
	 */
	private String guestPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestEmail
	 * @mbg.generated
	 */
	private String guestEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestAddress
	 * @mbg.generated
	 */
	private String guestAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestTitle
	 * @mbg.generated
	 */
	private String guestTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.newstatus
	 * @mbg.generated
	 */
	private String newstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_guest.guestContent
	 * @mbg.generated
	 */
	private String guestContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestId
	 * @return  the value of tb_guest.guestId
	 * @mbg.generated
	 */
	public Integer getGuestId() {
		return guestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestId
	 * @param guestId  the value for tb_guest.guestId
	 * @mbg.generated
	 */
	public void setGuestId(Integer guestId) {
		this.guestId = guestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestName
	 * @return  the value of tb_guest.guestName
	 * @mbg.generated
	 */
	public String getGuestName() {
		return guestName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestName
	 * @param guestName  the value for tb_guest.guestName
	 * @mbg.generated
	 */
	public void setGuestName(String guestName) {
		this.guestName = guestName == null ? null : guestName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestPhone
	 * @return  the value of tb_guest.guestPhone
	 * @mbg.generated
	 */
	public String getGuestPhone() {
		return guestPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestPhone
	 * @param guestPhone  the value for tb_guest.guestPhone
	 * @mbg.generated
	 */
	public void setGuestPhone(String guestPhone) {
		this.guestPhone = guestPhone == null ? null : guestPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestEmail
	 * @return  the value of tb_guest.guestEmail
	 * @mbg.generated
	 */
	public String getGuestEmail() {
		return guestEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestEmail
	 * @param guestEmail  the value for tb_guest.guestEmail
	 * @mbg.generated
	 */
	public void setGuestEmail(String guestEmail) {
		this.guestEmail = guestEmail == null ? null : guestEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestAddress
	 * @return  the value of tb_guest.guestAddress
	 * @mbg.generated
	 */
	public String getGuestAddress() {
		return guestAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestAddress
	 * @param guestAddress  the value for tb_guest.guestAddress
	 * @mbg.generated
	 */
	public void setGuestAddress(String guestAddress) {
		this.guestAddress = guestAddress == null ? null : guestAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestTitle
	 * @return  the value of tb_guest.guestTitle
	 * @mbg.generated
	 */
	public String getGuestTitle() {
		return guestTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestTitle
	 * @param guestTitle  the value for tb_guest.guestTitle
	 * @mbg.generated
	 */
	public void setGuestTitle(String guestTitle) {
		this.guestTitle = guestTitle == null ? null : guestTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.newstatus
	 * @return  the value of tb_guest.newstatus
	 * @mbg.generated
	 */
	public String getNewstatus() {
		return newstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.newstatus
	 * @param newstatus  the value for tb_guest.newstatus
	 * @mbg.generated
	 */
	public void setNewstatus(String newstatus) {
		this.newstatus = newstatus == null ? null : newstatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_guest.guestContent
	 * @return  the value of tb_guest.guestContent
	 * @mbg.generated
	 */
	public String getGuestContent() {
		return guestContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_guest.guestContent
	 * @param guestContent  the value for tb_guest.guestContent
	 * @mbg.generated
	 */
	public void setGuestContent(String guestContent) {
		this.guestContent = guestContent == null ? null : guestContent.trim();
	}
}