package edu.gdkm.po;

public class Newscolumn {

	@Override
	public String toString() {
		return "Newscolumn{" +
				"newsColumnId=" + newsColumnId +
				", parentId=" + parentId +
				", columnCode='" + columnCode + '\'' +
				", columnName='" + columnName + '\'' +
				", status='" + status + '\'' +
				'}';
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_newscolumn.newsColumnId
	 * @mbg.generated
	 */
	private Integer newsColumnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_newscolumn.parentId
	 * @mbg.generated
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_newscolumn.columnCode
	 * @mbg.generated
	 */
	private String columnCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_newscolumn.columnName
	 * @mbg.generated
	 */
	private String columnName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_newscolumn.status
	 * @mbg.generated
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_newscolumn.newsColumnId
	 * @return  the value of tb_newscolumn.newsColumnId
	 * @mbg.generated
	 */
	public Integer getNewsColumnId() {
		return newsColumnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_newscolumn.newsColumnId
	 * @param newsColumnId  the value for tb_newscolumn.newsColumnId
	 * @mbg.generated
	 */
	public void setNewsColumnId(Integer newsColumnId) {
		this.newsColumnId = newsColumnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_newscolumn.parentId
	 * @return  the value of tb_newscolumn.parentId
	 * @mbg.generated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_newscolumn.parentId
	 * @param parentId  the value for tb_newscolumn.parentId
	 * @mbg.generated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_newscolumn.columnCode
	 * @return  the value of tb_newscolumn.columnCode
	 * @mbg.generated
	 */
	public String getColumnCode() {
		return columnCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_newscolumn.columnCode
	 * @param columnCode  the value for tb_newscolumn.columnCode
	 * @mbg.generated
	 */
	public void setColumnCode(String columnCode) {
		this.columnCode = columnCode == null ? null : columnCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_newscolumn.columnName
	 * @return  the value of tb_newscolumn.columnName
	 * @mbg.generated
	 */
	public String getColumnName() {
		return columnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_newscolumn.columnName
	 * @param columnName  the value for tb_newscolumn.columnName
	 * @mbg.generated
	 */
	public void setColumnName(String columnName) {
		this.columnName = columnName == null ? null : columnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_newscolumn.status
	 * @return  the value of tb_newscolumn.status
	 * @mbg.generated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_newscolumn.status
	 * @param status  the value for tb_newscolumn.status
	 * @mbg.generated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}
}